"""
Revised HCBS Service Mappings
Manual corrections from domain expert review
Confidence: Medium-High
"""

REVISED_MAPPINGS = {
    # Taxonomy Code 1: Case Management
    "ABI Waiver Support Coordination": (1, "Case Management"),
    "Care Advisor": (1, "Case Management"),
    "Care Advisor (CHOICE Option only)": (1, "Case Management"),
    "Community Support Coordination": (1, "Case Management"),
    "Community Supports Coordinator": (1, "Case Management"),
    "Coordinated Caregiving": (1, "Case Management"),
    "Health Care Integration": (1, "Case Management"),
    "Independence Advisor": (1, "Case Management"),
    "Local Area Support Coordination Liaison": (1, "Case Management"),
    "Personal Plan Facilitation": (1, "Case Management"),
    "Professional Assessment and Monitoring": (1, "Case Management"),
    "Resource Coordination": (1, "Case Management"),
    "Service Management": (1, "Case Management"),
    "Support Coordination": (1, "Case Management"),
    "Support Coordination (SC)": (1, "Case Management"),
    "Supports Coordination": (1, "Case Management"),
    "Transition Intensive Support Coordination": (1, "Case Management"),
    "Waiver Support Coordination": (1, "Case Management"),
    "Community Choice Guiding": (1, "Case Management"),
    # Taxonomy Code 2: Round-the-Clock Services
    "Adult Care Home Service": (2, "Round-the-Clock Services"),
    "Adult Family Foster Care": (2, "Round-the-Clock Services"),
    "Adult Foster Care": (2, "Round-the-Clock Services"),
    "Adult Residential for Care for Acquired Traumatic Brain Injury Participants": (
        2,
        "Round-the-Clock Services",
    ),
    "Adult Residential Services": (2, "Round-the-Clock Services"),
    "Alternative Care Facility (ACF)": (2, "Round-the-Clock Services"),
    "Alternative Living Service": (2, "Round-the-Clock Services"),
    "Alternative Living Services (ALS)": (2, "Round-the-Clock Services"),
    "Assisted Living": (2, "Round-the-Clock Services"),
    "Assisted Living (ALR or CPCH)": (2, "Round-the-Clock Services"),
    "Assisted Living Facility": (2, "Round-the-Clock Services"),
    "Assisted Living Program (ALP) in Subsidized Housing": (
        2,
        "Round-the-Clock Services",
    ),
    "Assisted Living Service": (2, "Round-the-Clock Services"),
    "Assisted Living Service Level I": (2, "Round-the-Clock Services"),
    "Assisted Living Service Level II": (2, "Round-the-Clock Services"),
    "Assisted Living Service Level III": (2, "Round-the-Clock Services"),
    "Assisted Living Services": (2, "Round-the-Clock Services"),
    "ASSISTED LIVING SERVICES": (2, "Round-the-Clock Services"),
    "CBRF": (2, "Round-the-Clock Services"),
    "Community Based Residential Facility": (2, "Round-the-Clock Services"),
    "Community Living Home": (2, "Round-the-Clock Services"),
    "Community Living Support Benefit (CLSB) In Licensed Settings": (
        2,
        "Round-the-Clock Services",
    ),
    "Continuous Residential Supports": (2, "Round-the-Clock Services"),
    "Enhanced Residential Services": (2, "Round-the-Clock Services"),
    "Facilities licensed by the State as Nursing Facilities": (
        2,
        "Round-the-Clock Services",
    ),
    "Living Choices Assisted Living Services": (2, "Round-the-Clock Services"),
    "Non-Relative Adult Foster Care": (2, "Round-the-Clock Services"),
    "Relative Adult Foster Care": (2, "Round-the-Clock Services"),
    "Residential Services": (2, "Round-the-Clock Services"),
    "Residential Supported Living Services": (2, "Round-the-Clock Services"),
    "Residential Supports": (2, "Round-the-Clock Services"),
    "Special Family Habilitation Home": (2, "Round-the-Clock Services"),
    "Specialized Living Services": (2, "Round-the-Clock Services"),
    "Supplemental Protective Supervision": (2, "Round-the-Clock Services"),
    "Supported Family Living": (2, "Round-the-Clock Services"),
    "Supportive Housing Services": (2, "Round-the-Clock Services"),
    "Supportive Housing Services (formerly two services: Assisted Living and Congregate Care)": (
        2,
        "Round-the-Clock Services",
    ),
    # Taxonomy Code 3: Supported Employment
    "Career Assessment": (3, "Supported Employment"),
    "Career Exploration": (3, "Supported Employment"),
    "Career Preparation Services": (3, "Supported Employment"),
    "Customized Employment Supports": (3, "Supported Employment"),
    "Discovery/Career Exploration Services": (3, "Supported Employment"),
    "Employment Assistance": (3, "Supported Employment"),
    "Employment Discovery and Customization": (3, "Supported Employment"),
    "Employment Path Services": (3, "Supported Employment"),
    "Employment Skills Development": (3, "Supported Employment"),
    "Employment Specialist Services": (3, "Supported Employment"),
    "Employment Supports": (3, "Supported Employment"),
    "Integrated Community Employment": (3, "Supported Employment"),
    "Job Coaching": (3, "Supported Employment"),
    "Job Coaching (Intensive and Extended Follow-along)": (3, "Supported Employment"),
    "Job Discovery/Job Preparation": (3, "Supported Employment"),
    "Job Finding": (3, "Supported Employment"),
    "Long Term Vocational Supports": (3, "Supported Employment"),
    "Mentoring": (3, "Supported Employment"),
    "Vocational and Futures Planning": (3, "Supported Employment"),
    "Vocational Futures Planning": (3, "Supported Employment"),
    "Vocational Futures Planning and Support": (3, "Supported Employment"),
    "Work Support": (3, "Supported Employment"),
    # Taxonomy Code 4: Day Services
    "Adult Medical Day Services": (4, "Day Services"),
    "Community Engagement": (4, "Day Services"),
    "Community Living and Day Supports (CLDS)": (4, "Day Services"),
    "Day Activity": (4, "Day Services"),
    "Day Services": (4, "Day Services"),
    "Day Services - Adult": (4, "Day Services"),
    "Day Services for Adults": (4, "Day Services"),
    "Day Supports": (4, "Day Services"),
    "Day Supports and Activities": (4, "Day Services"),
    "Employment and Day Services": (4, "Day Services"),
    "Facility-Based Day Supports": (4, "Day Services"),
    "Habilitation - Day center service": (4, "Day Services"),
    "Individualized Day Supports": (4, "Day Services"),
    "Individualized skills and socialization": (4, "Day Services"),
    "Social Day Care": (4, "Day Services"),
    "Social, Leisure and Recreational Supports": (4, "Day Services"),
    "Structured Day Program Services": (4, "Day Services"),
    "Structured Day Program Services (SDP)": (4, "Day Services"),
    "Supportive Day Program": (4, "Day Services"),
    # Taxonomy Code 5: Nursing
    "Direct Nursing": (5, "Nursing"),
    "Extended Home Care Nursing": (5, "Nursing"),
    "Medication Administration": (5, "Nursing"),
    "Medication Administration Assistance Services": (5, "Nursing"),
    "Nurse Delegation": (5, "Nursing"),
    "Nursing": (5, "Nursing"),
    "Nursing Evaluation Visit": (5, "Nursing"),
    "Nursing Services": (5, "Nursing"),
    "Nursing Supervision": (5, "Nursing"),
    "Preventive Nursing Services": (5, "Nursing"),
    "Residential Nursing": (5, "Nursing"),
    "Residential Nursing Services": (5, "Nursing"),
    "Skilled Nurses Services (SNS)": (5, "Nursing"),
    "Skilled services provided by a Licensed Practical Nurse": (5, "Nursing"),
    "Skilled Services provided by a Registered Nurse": (5, "Nursing"),
    "Waiver Nursing": (5, "Nursing"),
    "Waiver Nursing Service": (5, "Nursing"),
    "Waiver Nursing Services": (5, "Nursing"),
    # Taxonomy Code 6: Home-Delivered Meals
    "Alternative Meals Service": (6, "Home-Delivered Meals"),
    "Home-Deliverd Meals": (6, "Home-Delivered Meals"),
    "Meal Preparation and Delivery": (6, "Home-Delivered Meals"),
    "Meals": (6, "Home-Delivered Meals"),
    "Meals and Nutritional Supplements": (6, "Home-Delivered Meals"),
    "Meals on Wheels": (6, "Home-Delivered Meals"),
    "Supplemental Meals": (6, "Home-Delivered Meals"),
    # Taxonomy Code 7: Rent and Food for Live-In Caregiver
    "Caregiver Living Expenses": (7, "Rent and Food for Live-In Caregiver"),
    # Taxonomy Code 8: Home-Based Services
    "Adult Daily Living": (8, "Home-Based Services"),
    "Adult Daily Living Services": (8, "Home-Based Services"),
    "Advanced Supportive/Restorative Assistance": (8, "Home-Based Services"),
    "Agencies licensed by the State under RSA 151:2 for home care": (
        8,
        "Home-Based Services",
    ),
    "Attendent Care": (8, "Home-Based Services"),
    "Choices - Home Care Attendant Service": (8, "Home-Based Services"),
    "Community Habilitation": (8, "Home-Based Services"),
    "Community Living and Support": (8, "Home-Based Services"),
    "Community Living Services": (8, "Home-Based Services"),
    "Community Supported Living": (8, "Home-Based Services"),
    "Community Supported Living Arrangements": (8, "Home-Based Services"),
    "Customized Living Services": (8, "Home-Based Services"),
    "Enhanced Community Living Service": (8, "Home-Based Services"),
    "Extended Home Health Care": (8, "Home-Based Services"),
    "Extended Home Health Services": (8, "Home-Based Services"),
    "Extended State Plan Home Health Care Services": (8, "Home-Based Services"),
    "Habilitation": (8, "Home-Based Services"),
    "Habilitation Training Specialist Services": (8, "Home-Based Services"),
    "Home Again Services": (8, "Home-Based Services"),
    "Home and Community Support Services": (8, "Home-Based Services"),
    "Home and Community Support Services (HCSS)": (8, "Home-Based Services"),
    "Home Care Agency": (8, "Home-Based Services"),
    "Home Care Attendant": (8, "Home-Based Services"),
    "Home Care Attendant (HCAS)": (8, "Home-Based Services"),
    "Home Care Attendant Services": (8, "Home-Based Services"),
    "Home Health": (8, "Home-Based Services"),
    "Home Health Care": (8, "Home-Based Services"),
    "Home Health Services": (8, "Home-Based Services"),
    "Home Maintenance Services": (8, "Home-Based Services"),
    "Home Support-Per Diem": (8, "Home-Based Services"),
    "Home Support-Remote Support": (8, "Home-Based Services"),
    "Home-Based Supportive Care": (8, "Home-Based Services"),
    "Independent Habilitation": (8, "Home-Based Services"),
    "Independent Living": (8, "Home-Based Services"),
    "Independent Living Assistance": (8, "Home-Based Services"),
    "Independent Living Assistance (End date eff. 6/30/19)": (8, "Home-Based Services"),
    "Independent Living Supports": (8, "Home-Based Services"),
    "Individualized Supported Living": (8, "Home-Based Services"),
    "Living Supports": (8, "Home-Based Services"),
    "Paraprofessional Services": (8, "Home-Based Services"),
    "Personal Assistant Services": (8, "Home-Based Services"),
    "Personal Assistant Services (CHOICE Option only)": (8, "Home-Based Services"),
    "Personal Supports": (8, "Home-Based Services"),
    "Pest Control": (8, "Home-Based Services"),
    "Pest Control-Initial Visit": (8, "Home-Based Services"),
    "Pest Control-Maintenance": (8, "Home-Based Services"),
    "Pest Control Services": (8, "Home-Based Services"),
    "Pest Eradication Services": (8, "Home-Based Services"),
    "Self Help Assistant": (8, "Home-Based Services"),
    "Supplemental Professional Care Assistance": (8, "Home-Based Services"),
    "Supported Living": (8, "Home-Based Services"),
    "Supportive Home Care": (8, "Home-Based Services"),
    "Supportive Maintenance Services": (8, "Home-Based Services"),
    "Community Direct Support": (8, "Home-Based Services"),
    # Taxonomy Code 9: Caregiver Support
    "Alzheimer's/Dementia Coaching": (9, "Caregiver Support"),
    "Caregiver/Family Advocacy and Support Services": (9, "Caregiver Support"),
    "Caregiver/Recipient Training": (9, "Caregiver Support"),
    "Caregiver/Recipient Training Services": (9, "Caregiver Support"),
    "Consultative Clinical and Therapeutic Services for Caregivers": (
        9,
        "Caregiver Support",
    ),
    "Family and Peer Mentoring": (9, "Caregiver Support"),
    "Family Care Option": (9, "Caregiver Support"),
    "Family Education": (9, "Caregiver Support"),
    "Family Support Services": (9, "Caregiver Support"),
    "Family Support Specialist": (9, "Caregiver Support"),
    "Family/Caregiver Supports and Services": (9, "Caregiver Support"),
    "Structured Family Caregiving": (2, "Round-the-Clock Services"),
    "Training Services for Unpaid Caregivers": (9, "Caregiver Support"),
    # Taxonomy Code 10: Other Mental Health and Behavioral Services
    "ABA certified Clinician": (10, "Other Mental Health and Behavioral Services"),
    "Addiction Services": (10, "Other Mental Health and Behavioral Services"),
    "Applied Behavior Analysis": (10, "Other Mental Health and Behavioral Services"),
    "Applied Behavior Analysis (ABA)": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Behavior Analysis Service": (10, "Other Mental Health and Behavioral Services"),
    "Behavior Assistant Services": (10, "Other Mental Health and Behavioral Services"),
    "Behavior Consultant": (10, "Other Mental Health and Behavioral Services"),
    "Behavior Services": (10, "Other Mental Health and Behavioral Services"),
    "Behavioral Assessment and Intervention": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Behavioral Intervention Assistant": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Behavioral Management and Education": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Behavioral Programming": (10, "Other Mental Health and Behavioral Services"),
    "Behavioral Risk Services": (10, "Other Mental Health and Behavioral Services"),
    "Behavioral Services": (10, "Other Mental Health and Behavioral Services"),
    "Behavioral Supports": (10, "Other Mental Health and Behavioral Services"),
    "Community Crisis Stabilization": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Community Psychiatric Support and Treatment": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Community Psychiatric Support and Treatment (CPST)": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Consultative Behavioral Intervention Services": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Consultative Clinical and Therapeutic - Psychological Services": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Consultative Clinical and Therapeutic Services - Positive Behavior Supports": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Avoidance and Management and Training": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Response Services": (10, "Other Mental Health and Behavioral Services"),
    "Crisis Services": (10, "Other Mental Health and Behavioral Services"),
    "Early Intensive Behavioral Intervention (EIBI)": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Early Intensive Behavioral Intervention Services": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "EIBI Program Development and Training": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Immediate Crisis Response Services": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Positive and Behavioral Interventions and Supports Services": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Positive and Behavioral Interventions and Supports Services (PBIS)": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Psychological Services": (10, "Other Mental Health and Behavioral Services"),
    "Recovery Assistant": (10, "Other Mental Health and Behavioral Services"),
    "Therapeutic Management of Substance Abuse": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    # Taxonomy Code 11: Other Health and Therapeutic Services
    "Audiology": (11, "Other Health and Therapeutic Services"),
    "Audiology Services": (11, "Other Health and Therapeutic Services"),
    "Audiology Treatment & Evaluation": (11, "Other Health and Therapeutic Services"),
    "Cognitive Retraining": (11, "Other Health and Therapeutic Services"),
    "Community Health Worker": (11, "Other Health and Therapeutic Services"),
    "Consultative Clinical and Therapeutic - Nutritional Services": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Consultative Clinical and Therapeutic Services": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Dietary": (11, "Other Health and Therapeutic Services"),
    "Dietetic Services": (11, "Other Health and Therapeutic Services"),
    "Dietician Nutrition Services": (11, "Other Health and Therapeutic Services"),
    "Dietitian/Nutritionist Services": (11, "Other Health and Therapeutic Services"),
    "Enteral Nutrition": (11, "Other Health and Therapeutic Services"),
    "Extended Medicaid State Plan Prescription Drugs": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Health and Wellness": (11, "Other Health and Therapeutic Services"),
    "Health/Health Maintenance/Safety Supports": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Home Visits by Medical Personnel": (11, "Other Health and Therapeutic Services"),
    "Hospice Care": (11, "Other Health and Therapeutic Services"),
    "Medical Risk Services": (11, "Other Health and Therapeutic Services"),
    "Medical Social Services": (11, "Other Health and Therapeutic Services"),
    "Nutrition": (11, "Other Health and Therapeutic Services"),
    "Nutrition Services": (11, "Other Health and Therapeutic Services"),
    "Nutritional Assessment and Risk Reduction": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Nutritional Education Services": (11, "Other Health and Therapeutic Services"),
    "Nutritional Risk Reduction": (11, "Other Health and Therapeutic Services"),
    "Nutritional Services": (11, "Other Health and Therapeutic Services"),
    "Nutritionist Services": (11, "Other Health and Therapeutic Services"),
    "Orientation and Mobility Services": (11, "Other Health and Therapeutic Services"),
    "Pain and Symptom Management": (11, "Other Health and Therapeutic Services"),
    "Palliative care – Pain and Symptom Management": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Post Acute Rehabilitation Services": (11, "Other Health and Therapeutic Services"),
    "Prescription drugs": (11, "Other Health and Therapeutic Services"),
    "Prescription Drugs": (11, "Other Health and Therapeutic Services"),
    "Prescription Medications": (11, "Other Health and Therapeutic Services"),
    "Psychiatry": (11, "Other Health and Therapeutic Services"),
    "Removable Prosthodontic Services": (11, "Other Health and Therapeutic Services"),
    "Restorative Massage": (11, "Other Health and Therapeutic Services"),
    "Skilled services provided by a Respiratory Therapist": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Social Work": (11, "Other Health and Therapeutic Services"),
    "Special Drug and Nutritional Assessment Services": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Specialized Medical Care": (11, "Other Health and Therapeutic Services"),
    "Speech and Hearing Services": (11, "Other Health and Therapeutic Services"),
    "Speech, Hearing and Language Services": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Supplemental Health Care": (11, "Other Health and Therapeutic Services"),
    "Therapy Services: Occupational": (11, "Other Health and Therapeutic Services"),
    "Therapy Services: Physical": (11, "Other Health and Therapeutic Services"),
    "Therapy Services: Respiratory": (11, "Other Health and Therapeutic Services"),
    "Therapy Services: Speech": (11, "Other Health and Therapeutic Services"),
    "Therapy: Occupational": (11, "Other Health and Therapeutic Services"),
    "Therapy: Physical": (11, "Other Health and Therapeutic Services"),
    "Therapy: Speech": (11, "Other Health and Therapeutic Services"),
    "Treatment and Health Maintenance": (11, "Other Health and Therapeutic Services"),
    "Vision Services to include Eye exam & Glasses": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Wellness Coaching": (11, "Other Health and Therapeutic Services"),
    # Taxonomy Code 12: Self-direction and Supporting Services
    "Agency with Choice": (12, "Self-direction and Supporting Services"),
    "Community Support Services (Participant Direction)": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consultant/Support Guide": (12, "Self-direction and Supporting Services"),
    "Consumer Directed Attendant Support Services": (8, "Home-Based Services"),
    "Consumer Directed Attendant Support Services (CDASS)": (8, "Home-Based Services"),
    "Consumer Directed Community Supports: Treatment and Training": (
        8,
        "Home-Based Services",
    ),
    "Consumer Directed Services Facilitation": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Supports (Self-Directed Supports) Broker": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Preparation Services": (12, "Self-direction and Supporting Services"),
    "Consumer-directed supports (Self-directed supports) support broker": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Financial Education and Protective Services": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Financial Support Services": (12, "Self-direction and Supporting Services"),
    "Fiscal / Employer Agent Services": (12, "Self-direction and Supporting Services"),
    "Fiscal Employer Agent Services": (12, "Self-direction and Supporting Services"),
    "Fiscal Management Services": (12, "Self-direction and Supporting Services"),
    "Independent Advocacy": (12, "Self-direction and Supporting Services"),
    "IRIS Consultant Services": (12, "Self-direction and Supporting Services"),
    "Participant Directed and Managed Services": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Participant-Directed Community Supports": (8, "Home-Based Services"),
    "Peer Guidance for Participant-Directed Care": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Personal Budget Assistance": (12, "Self-direction and Supporting Services"),
    "Self Directed Supports": (12, "Self-direction and Supporting Services"),
    "Services Facilitation": (12, "Self-direction and Supporting Services"),
    "Support Broker": (12, "Self-direction and Supporting Services"),
    "Supports Broker Services": (12, "Self-direction and Supporting Services"),
    "Supports Brokerage": (12, "Self-direction and Supporting Services"),
    # Taxonomy Code 13: Participant Training
    "Client Support Training": (13, "Participant Training"),
    "Client Support Training & Wellness Education": (13, "Participant Training"),
    "Community Coaching": (13, "Participant Training"),
    "Consumer Education & Training": (13, "Participant Training"),
    "Consumer Education and Training": (13, "Participant Training"),
    "Daily Living Skills Training": (13, "Participant Training"),
    "Education and Support": (13, "Participant Training"),
    "Education and Support Services": (13, "Participant Training"),
    "Education Support Services": (13, "Participant Training"),
    "Educational Services": (4, "Day Services"),
    "Evidence Based Education Programs": (13, "Participant Training"),
    "Independent Living Skills Training": (13, "Participant Training"),
    "Independent Living Skills Training Services": (13, "Participant Training"),
    "Independent Living Skills Training Services (ILST)": (13, "Participant Training"),
    "Independent Living/Skills Building": (13, "Participant Training"),
    "Independent Skills Building": (13, "Participant Training"),
    "Life Skills Training": (13, "Participant Training"),
    "Peer Mentoring": (10, "Other Mental Health and Behavioral Services"),
    "Skill Building": (13, "Participant Training"),
    "Skill Building Services": (13, "Participant Training"),
    "Skills training": (13, "Participant Training"),
    "Training": (13, "Participant Training"),
    "Training and Education Services": (13, "Participant Training"),
    "Training and Educational Supports": (13, "Participant Training"),
    "Training/Education and Consultative Services": (13, "Participant Training"),
    "Youth Peer Advocate": (10, "Other Mental Health and Behavioral Services"),
    # Taxonomy Code 14: Equipment, Technology, and Modifications
    "Accessibility Modifications": (14, "Equipment, Technology, and Modifications"),
    "Adaptive Aids": (14, "Equipment, Technology, and Modifications"),
    "Adaptive Aids and Supports": (14, "Equipment, Technology, and Modifications"),
    "Assistive Devices": (14, "Equipment, Technology, and Modifications"),
    "Assistive Services": (14, "Equipment, Technology, and Modifications"),
    "Emergency Response": (14, "Equipment, Technology, and Modifications"),
    "Emergency Response Service": (14, "Equipment, Technology, and Modifications"),
    "Emergency Response System": (14, "Equipment, Technology, and Modifications"),
    "Emergency Response System (ERS)": (14, "Equipment, Technology, and Modifications"),
    "Environment Accessibility and Adaptation Services": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accesibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Access and Modification": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations (EAA)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations (Home Modifications)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations (offered 7/1/11-1/5/14 only)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations and Architectural Modification": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations-Home": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Adaptations-Vehicle": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessibility Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental accessibility services": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Accessiblity Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Adaptations": (14, "Equipment, Technology, and Modifications"),
    "Environmental and Minor Home Adaptation": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental and Minor Home Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental and Minor Home Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental and Vehicle Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Assessment": (14, "Equipment, Technology, and Modifications"),
    "Environmental Assessments": (14, "Equipment, Technology, and Modifications"),
    "Environmental Assessments (offered 7/1/11-1/5/14 only)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Safety Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental Safety Services": (14, "Equipment, Technology, and Modifications"),
    "Environmental Supports/Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Environmental/Residential Modification": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Equipment, Modification and Technology": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home Adaptations": (14, "Equipment, Technology, and Modifications"),
    "Home Accessibility Adaptations": (14, "Equipment, Technology, and Modifications"),
    "Home Based Wandering Response Systems": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home Modifications": (14, "Equipment, Technology, and Modifications"),
    "Medication Dispensing System": (14, "Equipment, Technology, and Modifications"),
    "Minor Home Modifications": (14, "Equipment, Technology, and Modifications"),
    "Nutritional Supplements": (14, "Equipment, Technology, and Modifications"),
    "Related Goods": (14, "Equipment, Technology, and Modifications"),
    "Rehabilitation Engineering Evaluation": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Supplemental Adaptive and Assistive Device Services": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "TeleCare": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Modifications": (14, "Equipment, Technology, and Modifications"),
    "Vehicular Modification": (14, "Equipment, Technology, and Modifications"),
    "Wanderer Alarm System": (14, "Equipment, Technology, and Modifications"),
    "Wanderer Identification and Location System": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    # Taxonomy Code 15: Non-Medical Transportation
    "Non Medical Transportation": (15, "Non-Medical Transportation"),
    "Non-Medical Transporation": (15, "Non-Medical Transportation"),
    "Non-Medical Transportation": (15, "Non-Medical Transportation"),
    "Non-Medical Transportation Services": (15, "Non-Medical Transportation"),
    "Transportation - Non-Medical": (15, "Non-Medical Transportation"),
    "Transportation Services (Non-medical)": (15, "Non-Medical Transportation"),
    # Taxonomy Code 16: Community Transition Services
    "Care Transitions": (16, "Community Transition Services"),
    "Community Transition": (16, "Community Transition Services"),
    "Community Transition Coordination": (16, "Community Transition Services"),
    "Community Transition Supports": (16, "Community Transition Services"),
    "Community Transitional Services": (16, "Community Transition Services"),
    "Community Transitional Services (CTS)": (16, "Community Transition Services"),
    "Home Again Services": (16, "Community Transition Services"),
    "Housing Assistance": (16, "Community Transition Services"),
    "Housing Stabilization Services": (16, "Community Transition Services"),
    "Housing Stabilization Transition Service": (16, "Community Transition Services"),
    "Housing Start Up": (16, "Community Transition Services"),
    "Institution Transition Services": (16, "Community Transition Services"),
    "Institutional Transition Services": (16, "Community Transition Services"),
    "Main Attachment #1 Transition Plan": (99, "Unknown"),
    "Moving Assistance": (16, "Community Transition Services"),
    "Moving Assistance Services": (16, "Community Transition Services"),
    "NF Transition": (16, "Community Transition Services"),
    "Nursing Facility Transition Services": (16, "Community Transition Services"),
    "Nursing Home Transition Service": (16, "Community Transition Services"),
    "One-Time Transitional Services": (16, "Community Transition Services"),
    "Relocation - Housing Start Up and Related Utility Costs": (
        16,
        "Community Transition Services",
    ),
    "Relocation Related Housing Start-up.": (16, "Community Transition Services"),
    "Relocation Related Utilities": (16, "Community Transition Services"),
    "Relocation services": (16, "Community Transition Services"),
    "Transition Coordination": (16, "Community Transition Services"),
    "Transition Coordination (Month 1-6)": (16, "Community Transition Services"),
    "Transition Coordination (Month 7-12)": (16, "Community Transition Services"),
    "Transition Coordination (Pre-Discharge)": (16, "Community Transition Services"),
    "Transition Service": (16, "Community Transition Services"),
    "Transition Services": (16, "Community Transition Services"),
    "Transition Services (offered 7/1/11-1/5/14 only)": (
        16,
        "Community Transition Services",
    ),
    "Transition Services and Supports": (16, "Community Transition Services"),
    "Transition Setup": (16, "Community Transition Services"),
    "Transitional Assistance": (16, "Community Transition Services"),
    "Transitional Assistance Services": (16, "Community Transition Services"),
    "Transitional Environmental Accessibility Adaptations": (
        16,
        "Community Transition Services",
    ),
    "Transitional Living": (16, "Community Transition Services"),
    "Transitional Services": (16, "Community Transition Services"),
    # Taxonomy Code 17: Other Services
    "Child Support Services": (17, "Other Services"),
    "Community Development Services": (4, "Day Services"),
    "Community Specialist Services": (17, "Other Services"),
    "Community Support": (17, "Other Services"),
    "Community Support Services": (17, "Other Services"),
    "Community Supports": (17, "Other Services"),
    "Consolidated services": (17, "Other Services"),
    "Consultant Services": (17, "Other Services"),
    "Expanded Community Services": (17, "Other Services"),
    "Extended Services": (17, "Other Services"),
    "Managed Care Option - Capitated": (99, "Unknown"),
    "Non-Residental Support Services": (17, "Other Services"),
    "Protective Services": (17, "Other Services"),
    "Retirement Services": (17, "Other Services"),
    "Senior Care Options (SCO)": (17, "Other Services"),
    "Specialized Consultative Services": (17, "Other Services"),
    "Specialty Services": (17, "Other Services"),
    "Supplemental Supportive Services": (17, "Other Services"),
    # }
    # revised part 2
    # Taxonomy Code 1: Case Management
    "Community Navigator": (1, "Case Management"),
    "Consultative Assessment": (1, "Case Management"),
    # Taxonomy Code 2: Round-the-Clock Services
    "Host Home": (2, "Round-the-Clock Services"),
    "Supervision": (8, "Home-Based Services"),
    # Taxonomy Code 4: Day Services
    "Senior Center Plus": (4, "Day Services"),
    # Taxonomy Code 8: Home-Based Services
    "Home Support": (8, "Home-Based Services"),
    "Home Support (1/4 hour)": (8, "Home-Based Services"),
    "Home Support- 1/4 hour-Level I": (8, "Home-Based Services"),
    "Home Support-(1/4 hour)": (8, "Home-Based Services"),
    "Home Support-1/4 hour": (8, "Home-Based Services"),
    "Home Support-Per Diem Level II": (8, "Home-Based Services"),
    "Home Support-Per Diem Level III Increased Neurobehavioral": (
        8,
        "Home-Based Services",
    ),
    "Home-Based Agency Person-Centered Support": (8, "Home-Based Services"),
    "Intervener": (8, "Home-Based Services"),
    "Per Diem Home Support": (8, "Home-Based Services"),
    "Personal Assistant": (8, "Home-Based Services"),
    "Personal Assistant Service (PAS)": (8, "Home-Based Services"),
    "Pest Eradication": (8, "Home-Based Services"),
    # Taxonomy Code 9: Caregiver Support
    "Family Supports": (9, "Caregiver Support"),
    # Taxonomy Code 10: Other Mental Health and Behavioral Services
    "Center-based Crisis Supports": (10, "Other Mental Health and Behavioral Services"),
    "Community-based Crisis Supports": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Assessment": (10, "Other Mental Health and Behavioral Services"),
    "EIBI Assessment": (10, "Other Mental Health and Behavioral Services"),
    "EIBI Plan Implementation": (10, "Other Mental Health and Behavioral Services"),
    "High Fidelity Wraparound": (10, "Other Mental Health and Behavioral Services"),
    "Neuropsychological Evaluation": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Wraparound": (10, "Other Mental Health and Behavioral Services"),
    # Taxonomy Code 11: Other Health and Therapeutic Services
    "Adult Vision": (11, "Other Health and Therapeutic Services"),
    "Hospice": (11, "Other Health and Therapeutic Services"),
    "Infant Development": (11, "Other Health and Therapeutic Services"),
    "Nutritional Support": (11, "Other Health and Therapeutic Services"),
    "Orientation and Mobility": (11, "Other Health and Therapeutic Services"),
    "Palliative": (11, "Other Health and Therapeutic Services"),
    "Specialized Therapies": (11, "Other Health and Therapeutic Services"),
    # Taxonomy Code 12: Self-direction and Supporting Services
    "Benefits Planning": (3, "Supported Employment"),
    "Consumer and Family Directed Supports": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Community Supports: Self-direction Support Activities": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Employer Authority": (99, "Unknown"),
    "Service Facilitation": (12, "Self-direction and Supporting Services"),
    "Support Brokerage": (12, "Self-direction and Supporting Services"),
    # Taxonomy Code 13: Participant Training
    "Community Connector": (4, "Day Services"),
    "Education": (13, "Participant Training"),
    "Education Supports": (13, "Participant Training"),
    "Individualized Skill Development": (13, "Participant Training"),
    "Integrated Community Learning": (4, "Day Services"),
    "Special Instruction": (13, "Participant Training"),
    # Taxonomy Code 14: Equipment, Technology, and Modifications
    "Dietary Supplements": (11, "Other Health and Therapeutic Services"),
    "Home Accessibility Adapatations": (14, "Equipment, Technology, and Modifications"),
    "Home Accessibility and Adaptation": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home Modifications and Mobility Aids": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergancy Response System": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Remote Monitoring Service": (14, "Equipment, Technology, and Modifications"),
    "Telemonitoring": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Adaptation": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Adaptations": (14, "Equipment, Technology, and Modifications"),
    # Taxonomy Code 16: Community Transition Services
    "Community Tranistion": (16, "Community Transition Services"),
    "Housing Stabilization Service": (16, "Community Transition Services"),
    "Transitional": (16, "Community Transition Services"),
    # Taxonomy Code 17: Other Services
    "Community Networking": (4, "Day Services"),
    "Community Specialist": (17, "Other Services"),
    "Community Support Service": (17, "Other Services"),
    "Consultations": (17, "Other Services"),
    "Customized Community Supports": (17, "Other Services"),
    "Special Needs Community Advocacy and Support": (17, "Other Services"),
    # Taxonomy Code 99: Unknown
    "Direct Service Worker": (99, "Unknown"),
    "Medicaid Agency": (99, "Unknown"),
    "Provided in Facility": (2, "Round-the-Clock Services"),
    "Provider Type Title": (99, "Unknown"),
    "Subsection(s)": (99, "Unknown"),
    # Taxonomy Code 1: Case Management
    "Community Navigator (CN)": (1, "Case Management"),
    "Person-Centered Plan Facilitation": (1, "Case Management"),
    "Resource Facilitation": (1, "Case Management"),
    # Taxonomy Code 2: Round-the-Clock Services
    "Adult Foster Support": (2, "Round-the-Clock Services"),
    "Child foster care": (2, "Round-the-Clock Services"),
    "Integrated Community Supports": (2, "Round-the-Clock Services"),
    "Life Sharing": (2, "Round-the-Clock Services"),
    "Supportive Family-based Alternatives": (2, "Round-the-Clock Services"),
    # Taxonomy Code 3: Supported Employment
    "Co-Worker Supports": (3, "Supported Employment"),
    # Taxonomy Code 4: Day Services
    "Community Connections": (4, "Day Services"),
    "Community Experience": (4, "Day Services"),
    "Community Life Engagment Development": (4, "Day Services"),
    # Taxonomy Code 5: Nursing
    "Intermittent Intensive Medical Care": (5, "Nursing"),
    "Supervisory Visit": (5, "Nursing"),
    # Taxonomy Code 6: Home-Delivered Meals
    "Home DeliveredMeals": (6, "Home-Delivered Meals"),
    "Home-DeliverdMeals": (6, "Home-Delivered Meals"),
    # Taxonomy Code 8: Home-Based Services
    "ABI Recovery Assistant": (8, "Home-Based Services"),
    "ABI Recovery Assistant II": (8, "Home-Based Services"),
    "CompanionService": (8, "Home-Based Services"),
    "Extermination of Bed Bugs": (8, "Home-Based Services"),
    "Individualized Home Supports": (8, "Home-Based Services"),
    "Intensive Personal Support": (8, "Home-Based Services"),
    "Intensive Personal Supports": (8, "Home-Based Services"),
    "Overnight Recovery Assistant": (8, "Home-Based Services"),
    "Personal Support": (8, "Home-Based Services"),
    "Remote Support": (8, "Home-Based Services"),
    "Remote Supports": (8, "Home-Based Services"),
    "Remote Supports and Monitoring": (8, "Home-Based Services"),
    # Taxonomy Code 9: Caregiver Support
    "Coordinated Family Supports": (9, "Caregiver Support"),
    "Family Person-Centered Support": (9, "Caregiver Support"),
    "Natural Supports Education": (9, "Caregiver Support"),
    # Taxonomy Code 10: Other Mental Health and Behavioral Services
    "Brief Episode Stabilization": (10, "Other Mental Health and Behavioral Services"),
    "Community Support Program": (10, "Other Mental Health and Behavioral Services"),
    "Crisis and Stabilization Service": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Site Person-Centered Support": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Support": (10, "Other Mental Health and Behavioral Services"),
    "Mobile Response": (10, "Other Mental Health and Behavioral Services"),
    "Professional Service Psychologist": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Professional Service Pyschologist": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Stabilization": (10, "Other Mental Health and Behavioral Services"),
    "Substance Abuse Programs": (10, "Other Mental Health and Behavioral Services"),
    # Taxonomy Code 11: Other Health and Therapeutic Services
    "Chiropractic Service": (11, "Other Health and Therapeutic Services"),
    "Enhanced Pharmacy": (11, "Other Health and Therapeutic Services"),
    "Hippotherapy": (11, "Other Health and Therapeutic Services"),
    "Lenses and Frames": (11, "Other Health and Therapeutic Services"),
    "Nutritional Consultations": (11, "Other Health and Therapeutic Services"),
    "Nutritional Risk Reduction  Complete this part for a renewal application or a new waiver that replaces": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Optometry": (11, "Other Health and Therapeutic Services"),
    "Paramedical Service": (11, "Other Health and Therapeutic Services"),
    "Prescription Lenses and Frames": (11, "Other Health and Therapeutic Services"),
    "Professional Service Dietician/Nutritionist": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Professional Service Social Worker": (11, "Other Health and Therapeutic Services"),
    "Specialized Driving Assessment": (11, "Other Health and Therapeutic Services"),
    "Specialty Telehealth and Assessment Team": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Speech and Language Pathology": (11, "Other Health and Therapeutic Services"),
    "Speech, Hearing, and Language": (11, "Other Health and Therapeutic Services"),
    "Therapies": (11, "Other Health and Therapeutic Services"),
    # Taxonomy Code 12: Self-direction and Supporting Services
    "Consumer Directed Community Supports (CDCS): Self-direction Support Activities": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Community Supports (CDCS): Support Planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Community Supports: support planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer-directed community supports (CDCS): Support Planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Independent Support Brokerage Service": (
        12,
        "Self-direction and Supporting Services",
    ),
    # Taxonomy Code 13: Participant Training
    "Community Mentor": (13, "Participant Training"),
    "Empowerment and Self-Determination Supports": (13, "Participant Training"),
    "Life Coach": (13, "Participant Training"),
    "Matter of Balance (Falls Prevention)": (13, "Participant Training"),
    "Mentorship": (13, "Participant Training"),
    "Parenting Support": (13, "Participant Training"),
    "Safety Planning and Prevention": (13, "Participant Training"),
    "Socialization and Sexuality Education": (13, "Participant Training"),
    "Specialized Skill Development": (13, "Participant Training"),
    "Supported Parenting": (13, "Participant Training"),
    # Taxonomy Code 14: Equipment, Technology, and Modifications
    "Activity and Sensor Monitoring (ASM)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Assistive Devices andEquipment": (14, "Equipment, Technology, and Modifications"),
    "Assistive Devices andEquipment (offered 7/1/11-1/5/14 only)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "AssistiveTechnology": (14, "Equipment, Technology, and Modifications"),
    "Electronic Home-based Supports": (14, "Equipment, Technology, and Modifications"),
    "Electronic Monitoring": (14, "Equipment, Technology, and Modifications"),
    "Home Accessibility Adaptations HCBS Taxonomy:": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home Accessibility Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home and Vehicle Modifications": (14, "Equipment, Technology, and Modifications"),
    "Home Modifications and Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home or Vehicle Accessibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Minor Home Repairs and Maintenance": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Minor Physical Adaptations to the Home": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystem": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Installation,Testing, and Removal": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Purchase,Rental,and Repair": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Response Center Service": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Private Vehicle Modifications": (14, "Equipment, Technology, and Modifications"),
    "Remote Monitoring": (14, "Equipment, Technology, and Modifications"),
    "Specialized Clothing": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Accessibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Vehicle Modifications (VM)": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Modifications and Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    # Taxonomy Code 16: Community Transition Services
    "Home Again": (16, "Community Transition Services"),
    "One-Time Transitional": (16, "Community Transition Services"),
    # Taxonomy Code 17: Other Services
    "Housing Access Supports": (17, "Other Services"),
    "Recreational Facility Fees/Passes": (17, "Other Services"),
    "Senior Supports": (17, "Other Services"),
    "Social Support": (17, "Other Services"),
    "Supplemental Support": (17, "Other Services"),
    # Revised part 3 ( 03/2026)
    # Taxonomy Code 1: Case Management
    "Community Navigator (CN)": (1, "Case Management"),
    "Person-Centered Plan Facilitation": (1, "Case Management"),
    "Resource Facilitation": (1, "Case Management"),
    # Taxonomy Code 2: Round-the-Clock Services
    "Adult Foster Support": (2, "Round-the-Clock Services"),
    "Child foster care": (2, "Round-the-Clock Services"),
    "Integrated Community Supports": (2, "Round-the-Clock Services"),
    "Life Sharing": (2, "Round-the-Clock Services"),
    "Supportive Family-based Alternatives": (2, "Round-the-Clock Services"),
    # Taxonomy Code 3: Supported Employment
    "Co-Worker Supports": (3, "Supported Employment"),
    # Taxonomy Code 4: Day Services
    "Community Connections": (4, "Day Services"),
    "Community Experience": (4, "Day Services"),
    "Community Life Engagment Development": (4, "Day Services"),
    # Taxonomy Code 5: Nursing
    "Intermittent Intensive Medical Care": (5, "Nursing"),
    "Supervisory Visit": (5, "Nursing"),
    # Taxonomy Code 6: Home-Delivered Meals
    "Home DeliveredMeals": (6, "Home-Delivered Meals"),
    "Home-DeliverdMeals": (6, "Home-Delivered Meals"),
    # Taxonomy Code 8: Home-Based Services
    "ABI Recovery Assistant": (8, "Home-Based Services"),
    "ABI Recovery Assistant II": (8, "Home-Based Services"),
    "CompanionService": (8, "Home-Based Services"),
    "Extermination of Bed Bugs": (8, "Home-Based Services"),
    "Individualized Home Supports": (8, "Home-Based Services"),
    "Intensive Personal Support": (8, "Home-Based Services"),
    "Intensive Personal Supports": (8, "Home-Based Services"),
    "Overnight Recovery Assistant": (8, "Home-Based Services"),
    "Personal Support": (8, "Home-Based Services"),
    "Remote Support": (8, "Home-Based Services"),
    "Remote Supports": (8, "Home-Based Services"),
    "Remote Supports and Monitoring": (8, "Home-Based Services"),
    # Taxonomy Code 9: Caregiver Support
    "Coordinated Family Supports": (9, "Caregiver Support"),
    "Family Person-Centered Support": (9, "Caregiver Support"),
    "Natural Supports Education": (9, "Caregiver Support"),
    # Taxonomy Code 10: Other Mental Health and Behavioral Services
    "Brief Episode Stabilization": (10, "Other Mental Health and Behavioral Services"),
    "Community Support Program": (10, "Other Mental Health and Behavioral Services"),
    "Crisis and Stabilization Service": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Site Person-Centered Support": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Crisis Support": (10, "Other Mental Health and Behavioral Services"),
    "Mobile Response": (10, "Other Mental Health and Behavioral Services"),
    "Professional Service Psychologist": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Professional Service Pyschologist": (
        10,
        "Other Mental Health and Behavioral Services",
    ),
    "Stabilization": (10, "Other Mental Health and Behavioral Services"),
    "Substance Abuse Programs": (10, "Other Mental Health and Behavioral Services"),
    # Taxonomy Code 11: Other Health and Therapeutic Services
    "Chiropractic Service": (11, "Other Health and Therapeutic Services"),
    "Enhanced Pharmacy": (11, "Other Health and Therapeutic Services"),
    "Hippotherapy": (11, "Other Health and Therapeutic Services"),
    "Lenses and Frames": (11, "Other Health and Therapeutic Services"),
    "Nutritional Consultations": (11, "Other Health and Therapeutic Services"),
    "Nutritional Risk Reduction  Complete this part for a renewal application or a new waiver that replaces": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Optometry": (11, "Other Health and Therapeutic Services"),
    "Paramedical Service": (11, "Other Health and Therapeutic Services"),
    "Prescription Lenses and Frames": (11, "Other Health and Therapeutic Services"),
    "Professional Service Dietician/Nutritionist": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Professional Service Social Worker": (11, "Other Health and Therapeutic Services"),
    "Specialized Driving Assessment": (11, "Other Health and Therapeutic Services"),
    "Specialty Telehealth and Assessment Team": (
        11,
        "Other Health and Therapeutic Services",
    ),
    "Speech and Language Pathology": (11, "Other Health and Therapeutic Services"),
    "Speech, Hearing, and Language": (11, "Other Health and Therapeutic Services"),
    "Therapies": (11, "Other Health and Therapeutic Services"),
    # Taxonomy Code 12: Self-direction and Supporting Services
    "Consumer Directed Community Supports (CDCS): Self-direction Support Activities": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Community Supports (CDCS): Support Planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer Directed Community Supports: support planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Consumer-directed community supports (CDCS): Support Planning": (
        12,
        "Self-direction and Supporting Services",
    ),
    "Independent Support Brokerage Service": (
        12,
        "Self-direction and Supporting Services",
    ),
    # Taxonomy Code 13: Participant Training
    "Community Mentor": (13, "Participant Training"),
    "Empowerment and Self-Determination Supports": (13, "Participant Training"),
    "Life Coach": (13, "Participant Training"),
    "Matter of Balance (Falls Prevention)": (13, "Participant Training"),
    "Mentorship": (13, "Participant Training"),
    "Parenting Support": (13, "Participant Training"),
    "Safety Planning and Prevention": (13, "Participant Training"),
    "Socialization and Sexuality Education": (13, "Participant Training"),
    "Specialized Skill Development": (13, "Participant Training"),
    "Supported Parenting": (13, "Participant Training"),
    # Taxonomy Code 14: Equipment, Technology, and Modifications
    "Activity and Sensor Monitoring (ASM)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Assistive Devices andEquipment": (14, "Equipment, Technology, and Modifications"),
    "Assistive Devices andEquipment (offered 7/1/11-1/5/14 only)": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "AssistiveTechnology": (14, "Equipment, Technology, and Modifications"),
    "Electronic Home-based Supports": (14, "Equipment, Technology, and Modifications"),
    "Electronic Monitoring": (14, "Equipment, Technology, and Modifications"),
    "Home Accessibility Adaptations HCBS Taxonomy:": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home Accessibility Modifications": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home and Vehicle Modifications": (14, "Equipment, Technology, and Modifications"),
    "Home Modifications and Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Home or Vehicle Accessibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Minor Home Repairs and Maintenance": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Minor Physical Adaptations to the Home": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystem": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Installation,Testing, and Removal": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Purchase,Rental,and Repair": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Personal Emergency ResponseSystems Response Center Service": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Private Vehicle Modifications": (14, "Equipment, Technology, and Modifications"),
    "Remote Monitoring": (14, "Equipment, Technology, and Modifications"),
    "Specialized Clothing": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Accessibility Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    "Vehicle Modifications (VM)": (14, "Equipment, Technology, and Modifications"),
    "Vehicle Modifications and Adaptations": (
        14,
        "Equipment, Technology, and Modifications",
    ),
    # Taxonomy Code 16: Community Transition Services
    "Home Again": (16, "Community Transition Services"),
    "One-Time Transitional": (16, "Community Transition Services"),
    # Taxonomy Code 17: Other Services
    "Housing Access Supports": (17, "Other Services"),
    "Recreational Facility Fees/Passes": (17, "Other Services"),
    "Senior Supports": (17, "Other Services"),
    "Social Support": (17, "Other Services"),
    "Supplemental Support": (17, "Other Services"),
}
